In [3]:
import numpy as np
my_list = [1,2,3,4]
arr1 = np.array(my_list)

arr1, my_list

(array([1, 2, 3, 4]), [1, 2, 3, 4])

In [7]:
arr1 * 10 # element wise (1개값-scala로 본다 , 여러개값-벡터)
arr1 + 10

array([11, 12, 13, 14])

In [8]:
my_list * 10  # 연산이 아닌 내용 복제 반복
my_list + 10 # 오류남~

TypeError: can only concatenate list (not "int") to list

In [10]:
my_list2 = [
    [1,2,3],
    [4,5,6]
]
my_list2[1]

[4, 5, 6]

In [12]:
arr2 = np.array(my_list2)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr2[ : , 1] # [행번호, 열번호]  :은 전체

array([2, 5])

In [14]:
arr2 [ :, [0,2] ] # 팬시인덱싱(띄엄띄엄 추출)

array([[1, 3],
       [4, 6]])

In [19]:
#3차원 배열
arr3 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [20]:
np.arange(0, 3, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9])

In [31]:
np.ones()

TypeError: ones() missing 1 required positional argument: 'shape'

In [32]:
np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [ ]:
np.full()

In [23]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [33]:
arr1.ndim, arr2.ndim, arr3.ndim

(1, 2, 3)

In [38]:
arr1.shape #(4,)
arr2.shape #행,열 (2, 3)
arr3.shape #면,행,열 (2, 2, 3) 
arr3.size #저장된 총 갯수 12

12

In [35]:
type( (3,) )

tuple

In [44]:
np.array([1.0,2,3]) #array([1., 2., 3.])
np.array([1.0,2,"3"]) #array(['1.0', '2', '3'], dtype='<U32')
#U=유니코드 32:최대 32문자보다 적은거로 이루어져있음 (유니코드글자 최대 32자)


array(['1.0', '2', '3'], dtype='<U32')

In [45]:
arr1.dtype, arr2.dtype, arr3.dtype
# (dtype('int32'), dtype('int32'), dtype('int32'))
# int32 = 숫자 하나를 표현할때 32비트로 표현하겠다

(dtype('int32'), dtype('int32'), dtype('int32'))

In [46]:
arr2, arr2.T
'''
(array([[1, 2, 3],       2열 3행 데이터가
        [4, 5, 6]]),
 array([[1, 4],          3열 2행 데이터로 변환
        [2, 5],
        [3, 6]]))
'''

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 4],
        [2, 5],
        [3, 6]]))

In [50]:
arr4 = np.arange(16)

arr4.reshape(2,2, -1)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [53]:
x = np.array([[1,2], [3,4]], dtype=np.float64)
x, x.dtype
'''
(array([[1., 2.],
        [3., 4.]]),
 dtype('float64'))
'''

x.astype(np.int32) #array([[1, 2],[3, 4]])

array([[1, 2],
       [3, 4]])

In [55]:
arr2.dtype

dtype('int32')

In [56]:
arr2.astype( np.float32 )
#복사본을 바꾼것임. 원본은 그대로

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [57]:
arr2.dtype #원본

dtype('int32')

In [ ]:
아파트 실거래가 하고 옴

In [58]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr6 = np.arange(9)
arr6

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [63]:
arr6[1] #1
arr5[1] #array([3, 4, 5])
arr5[1][1] #4
arr5[1,1] #4

4

In [64]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
bidx = arr5 % 2 == 0
bidx

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

In [67]:
arr5[ bidx ] #ture에 위치하는 값을 추출하고 1차원으로 반환

array([0, 2, 4, 6, 8])

In [69]:
arr5[arr5 > 5]

array([6, 7, 8])

In [70]:
arr5[ arr5 % 2 == 0 ]

array([0, 2, 4, 6, 8])

In [72]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [73]:
arr5[ 0,2 ], arr5[ 1, 1 ]

(2, 4)

In [74]:
arr5[ [0,1], [2,1] ]

array([2, 4])

In [ ]:
'''
정수인덱싱
조건인덱싱
팬시인덱싱
'''

In [75]:
arr5[ 0, 2 ], arr5[1,1]

(2, 4)

In [83]:
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
arr5[ [0,1], [0,1] ]

array([0, 4])

In [78]:
arr5[0, :]

array([0, 1, 2])

In [81]:
arr5[ :2, 1: ]

array([[1, 2],
       [4, 5]])

In [82]:
arr5[-1:, 1:3]

array([[7, 8]])

In [84]:
b = arr5[ :,1 ]
b

array([1, 4, 7])

In [85]:
b[0] = 10
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [86]:
b=arr5[:,1].copy() #복사본
b

array([10,  4,  7])

In [87]:
b[0] = 1 #위 복사본의 카피를 한 녀석이라 원본arr5는 안바뀜~
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [88]:
np.where(arr5%2==0)

(array([0, 0, 0, 1, 2, 2], dtype=int64),
 array([0, 1, 2, 1, 0, 2], dtype=int64))

In [89]:
np.where(arr5%2==0, "짝수", "홀수") 
#앞은 조건에맞는 것을 대체해라, 뒤는 안맞는거

array([['짝수', '짝수', '짝수'],
       ['홀수', '짝수', '홀수'],
       ['짝수', '홀수', '짝수']], dtype='<U2')

In [92]:
# 조건에 맞는 항목은 "짝수", 아니면 안바꿈(원래값 유지)

#np.where(arr5%2==0, "짝수")
#오류남 ValueError: either both or neither of x and y should be given

np.where(arr5%2==0, "짝수", arr5)
#해당값을 그대로 쓰지않고 문자열로 바뀌어있음.
#문자열이 정수보다 값을 더 많이 표현할수있어서 자동으로 문자열로 바뀜
#numpy는 모든값이 동일한 타입이어야함. 한쪽이 문자면 다른쪽도 문자


array([['짝수', '짝수', '짝수'],
       ['3', '짝수', '5'],
       ['짝수', '7', '짝수']], dtype='<U11')

In [94]:
arr5

array([[ 0, 10,  2],
       [ 3,  4,  5],
       [ 6,  7,  8]])

In [95]:
arr5.sum()

45

In [96]:
arr5.sum(axis=0) #열 별 통계

array([ 9, 21, 15])

In [ ]:
'''
axis = 0 하면 행단위로 읽어서 내려감
행 단위로 읽어서 칼럼(열)별 통계를 냄
이동방향은 행방향
행을 읽었더니 그 안에 칼럼이 있음. 그럼 그 칼럼별 통계를 냄.
위에는 sum이니까 칼럼별 sum()해줌
axis= 1은 행 별 통계를 내준다
'''

In [97]:
arr5.sum(axis=1)

array([12, 12, 21])