# p.18 데이터 세트 불러오기

In [1]:
from sklearn.datasets import load_iris # 붓꽃 품종 데이터, 다중 분류
iris = load_iris()
iris, type(iris)

({'data': array([[5.1, 3.5, 1.4, 0.2],
         [4.9, 3. , 1.4, 0.2],
         [4.7, 3.2, 1.3, 0.2],
         [4.6, 3.1, 1.5, 0.2],
         [5. , 3.6, 1.4, 0.2],
         [5.4, 3.9, 1.7, 0.4],
         [4.6, 3.4, 1.4, 0.3],
         [5. , 3.4, 1.5, 0.2],
         [4.4, 2.9, 1.4, 0.2],
         [4.9, 3.1, 1.5, 0.1],
         [5.4, 3.7, 1.5, 0.2],
         [4.8, 3.4, 1.6, 0.2],
         [4.8, 3. , 1.4, 0.1],
         [4.3, 3. , 1.1, 0.1],
         [5.8, 4. , 1.2, 0.2],
         [5.7, 4.4, 1.5, 0.4],
         [5.4, 3.9, 1.3, 0.4],
         [5.1, 3.5, 1.4, 0.3],
         [5.7, 3.8, 1.7, 0.3],
         [5.1, 3.8, 1.5, 0.3],
         [5.4, 3.4, 1.7, 0.2],
         [5.1, 3.7, 1.5, 0.4],
         [4.6, 3.6, 1. , 0.2],
         [5.1, 3.3, 1.7, 0.5],
         [4.8, 3.4, 1.9, 0.2],
         [5. , 3. , 1.6, 0.2],
         [5. , 3.4, 1.6, 0.4],
         [5.2, 3.5, 1.5, 0.2],
         [5.2, 3.4, 1.4, 0.2],
         [4.7, 3.2, 1.6, 0.2],
         [4.8, 3.1, 1.6, 0.2],
         [5.4, 3.4, 1.5, 0.4],


seaborn에서 iris 불러오기

In [2]:
import seaborn as sns
iris2 = sns.load_dataset('iris')
iris2
# index, ~colum~, value
# species를 빼야 learning이 되겠죠?

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [5]:
type(iris2), iris2.keys()

(pandas.core.frame.DataFrame,
 Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
        'species'],
       dtype='object'))

In [4]:
type(iris.data), iris.data[:5], iris.data.shape, iris.feature_names # column

(numpy.ndarray,
 array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2]]),
 (150, 4),
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [6]:
type(iris.target), iris.target[:5], iris.target.shape # row

(numpy.ndarray, array([0, 0, 0, 0, 0]), (150,))

# p.20 데이터 분할

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

x = np.arange(10)

x_train, x_test = train_test_split(x) # 훈련, 평가용 데이터 분리
print(x_train)
print(x_test)

[7 4 0 8 1 9 3]
[6 5 2]


In [8]:
x_tr, x_te, y_tr, y_te = train_test_split(
    iris.data, #입력 2D
    iris.target, #답, 1D
    test_size=0.3, # 평가데이터 비율
    random_state=100 )#난수 생성 시드

    # iris['data'], iris['target'] 해도 됨!
    
x_tr.shape, x_te.shape, y_tr.shape, y_te.shape
# 0.7, 0.3, 0.7 , 0.3

((105, 4), (45, 4), (105,), (45,))

In [9]:
x_tr[:5], y_tr[:5] # 이거 똑같이 안나오면 큰 일

(array([[4.6, 3.4, 1.4, 0.3],
        [5. , 3. , 1.6, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [5.8, 2.6, 4. , 1.2],
        [4.9, 3.1, 1.5, 0.1]]),
 array([0, 0, 0, 1, 0]))

In [10]:
x_te[0:2], y_te[0:2] # test 결과

(array([[6.4, 2.8, 5.6, 2.1],
        [4.8, 3.4, 1.6, 0.2]]),
 array([2, 0]))

In [11]:
x_te[:5], y_te[:5]

(array([[6.4, 2.8, 5.6, 2.1],
        [4.8, 3.4, 1.6, 0.2],
        [7.7, 2.6, 6.9, 2.3],
        [5.7, 4.4, 1.5, 0.4],
        [6.3, 2.7, 4.9, 1.8]]),
 array([2, 0, 2, 0, 2]))

# p.22 K-NN  
최근접 알고리즘  
--> 각 데이터 간 유클리드 거리 계산(고딩 때 했던 점 거리 계산식), 
    가장 가까운 K개로 묶어주기!

# p.25 모델, 평가
    분류 모델 : KNeighborsClassifier
    회귀 모델 : KNeighborsRegressor

In [12]:
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(n_neighbors=3) # k-nn의 k, 조절 가능!
model.fit(x_tr, y_tr) # 훈련 코드

# 값 예측 출력, 입력값(반드시 2D!) 에 대한 예측값 출력
model.predict([[6.4, 2.8, 5.6, 2.1]]) # 예시 입력값 = x_te[0] => 출력값 = y_te[0]

print('예측값 : ', model.predict(x_te)) # 전체 test 예측
print('실제답 : ', y_te)

# 정확도 계산
pred = model.predict(x_te)
print( pred == y_te) # 내 답과 정답이 같아?
print( sum(pred == y_te) / len(y_te)) # 몇개 중 몇개?

예측값 :  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2 1 1 1 0 0 1 0
 1 2 2 0 1 2 2 0]
실제답 :  [2 0 2 0 2 2 0 0 2 0 0 2 0 0 2 1 1 1 2 2 2 0 2 0 1 2 1 0 1 2 1 1 2 0 0 1 0
 1 2 2 0 1 2 2 0]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False  True  True  True
  True  True  True  True  True  True  True  True  True]
0.9777777777777777


In [13]:
# 정확도 계산 (score)
print('훈련 데이터 : ', model.score(x_tr, y_tr))
print('평가 데이터 : ', model.score(x_te, y_te))

# 훈련 데이터가 1이 안나오는 경우 있음!

훈련 데이터 :  0.9619047619047619
평가 데이터 :  0.9777777777777777


In [14]:
iris2

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [15]:
x = iris2.drop(columns=['species']) # 정답 삭제된 입력값
y = iris2['species'] # label
x,y

(     sepal_length  sepal_width  petal_length  petal_width
 0             5.1          3.5           1.4          0.2
 1             4.9          3.0           1.4          0.2
 2             4.7          3.2           1.3          0.2
 3             4.6          3.1           1.5          0.2
 4             5.0          3.6           1.4          0.2
 ..            ...          ...           ...          ...
 145           6.7          3.0           5.2          2.3
 146           6.3          2.5           5.0          1.9
 147           6.5          3.0           5.2          2.0
 148           6.2          3.4           5.4          2.3
 149           5.9          3.0           5.1          1.8
 
 [150 rows x 4 columns],
 0         setosa
 1         setosa
 2         setosa
 3         setosa
 4         setosa
          ...    
 145    virginica
 146    virginica
 147    virginica
 148    virginica
 149    virginica
 Name: species, Length: 150, dtype: object)

In [16]:
x_tr, x_te, y_tr, y_te = train_test_split( # 7:3
    iris.data, #입력 2D
    iris.target, #답, 1D
    test_size=0.3, # 평가데이터 비율
    random_state=100 )#난수 생성 시드

x_tr.shape, x_te.shape, y_tr.shape, y_te.shape

((105, 4), (45, 4), (105,), (45,))

In [17]:
model = KNeighborsClassifier(n_neighbors=1) # k-nn의 k, 조절 가능!
model.fit(x_tr, y_tr) # 훈련 코드

print('훈련 데이터 : ', model.score(x_tr, y_tr))
print('평가 데이터 : ', model.score(x_te, y_te))

훈련 데이터 :  1.0
평가 데이터 :  0.9777777777777777


## fish.csv를 읽고 KNN으로 훈련, 성능평가점수 출력

In [20]:
import seaborn as sns
import pandas as pd
fish = pd.read_csv('./data/fish.csv')
fish

Species  Weight  Length  Diagonal   Height   Width
0     Bream   242.0    25.4      30.0  11.5200  4.0200
1     Bream   290.0    26.3      31.2  12.4800  4.3056
2     Bream   340.0    26.5      31.1  12.3778  4.6961
3     Bream   363.0    29.0      33.5  12.7300  4.4555
4     Bream   430.0    29.0      34.0  12.4440  5.1340
..      ...     ...     ...       ...      ...     ...
154   Smelt    12.2    12.2      13.4   2.0904  1.3936
155   Smelt    13.4    12.4      13.5   2.4300  1.2690
156   Smelt    12.2    13.0      13.8   2.2770  1.2558
157   Smelt    19.7    14.3      15.2   2.8728  2.0672
158   Smelt    19.9    15.0      16.2   2.9322  1.8792

[159 rows x 6 columns]

In [23]:
x = fish.drop(columns=['Species']) # 정답 삭제된 입력값
y = fish['Species'] # label

In [25]:
from sklearn.neighbors import KNeighborsClassifier

x_tr, x_te, y_tr, y_te = train_test_split(
    x,
    y,
    test_size=0.3, # 평가데이터 비율
    random_state=100 )#난수 생성 시드

x_tr.shape, x_te.shape, y_tr.shape, y_te.shape

model = KNeighborsClassifier(n_neighbors=3) # k-nn의 k, 조절 가능!
model.fit(x_tr, y_tr) # 훈련 코드

print('훈련 데이터 : ', model.score(x_tr, y_tr))
print('평가 데이터 : ', model.score(x_te, y_te))

훈련 데이터 :  0.7657657657657657
평가 데이터 :  0.5208333333333334


In [31]:
y_tr.value_counts() # 

Perch        40
Bream        23
Roach        13
Pike         12
Smelt         9
Parkki        9
Whitefish     5
Name: Species, dtype: int64

In [ ]:
/ fish["Species"].value_count()

In [32]:
# 데이터 프레임으로 모델 평가하기
# seaborn에서 iris 불러오기
import seaborn as sns
iris2 = sns.load_dataset('iris')
iris2

x =
y =


from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(
    x,
    y,
    test_size=0.3, # 평가데이터 비율
    random_state=100 )#난수 생성 시드
    
)

from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors=3)
model.fit(x_tr, y_tr)

k_range = range(1, 11)

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]